language: go
go:
  - "1.x"
go_import_path: github.com/everettcaleb/snowflake
services:
  - docker
install:
  - |
      # download test reporter as a static binary
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
  - go get -v -t -d ./...
script:
  - ./cc-test-reporter before-build
  - go test -v -coverprofile=c.out ./...
  - ./cc-test-reporter after-build
  - docker build -t everettcaleb/snowflake .
deploy:
  provider: script
  script: bash scripts/push-docker.sh
  skip_cleanup: true
  on:
    tags: true
