openapi: 3.0.1
info:
  title: snowflake
  version: 1.1.0
  description: An API that generates IDs inspired by Twitter's Snowflake formula
  license:
    name: MIT
components:
  schemas:
    HealthCheck:
      title: Health Check Response Body
      description: The body of a Health Check response
      type: object
      properties:
        status:
          type: string
          example: OK
      required:
        - status
    Snowflake:
      title: Snowflake
      description: A Snowflake ID in number and string form
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID as a uint64
        idStr:
          type: string
          description: ID as a string, for languages that may not support the full uint64 range (i.e. JavaScript)
      example: { "id":93464235379523584, "idStr":"93464235379523584" }
    Error:
      title: Error
      description: An error
      type: string
  responses:
    HealthCheckResponse:
      description: Response from doing a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HealthCheck'
    SnowflakeResponse:
      description: Response with a single Snowflake ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Snowflake'
    SnowflakeArrayResponse:
      description: Response with more than one Snowflake ID
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Snowflake'
    ErrorResponse:
      description: Response when an error occurred
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/Error'
paths:
  /:
    get:
      operationId: getSnowflake
      description: Gets a single Snowflake ID
      responses:
        '200':
          $ref: '#/components/responses/SnowflakeResponse'
  /{count}:
    get:
      operationId: getSnowflakes
      description: Get more than one Snowflake ID in one shot
      responses:
        '200':
          $ref: '#/components/responses/SnowflakeArrayResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
  /healthz:
    get:
      operationId: healthCheck
      description: Checks whether this service is available
      responses:
        '200':
          $ref: '#/components/responses/HealthCheckResponse'
  /spec.json:
    get:
      operationId: getSpecificationJson
      description: Gets this specification in JSON format
      responses:
        '200':
          description: This specification
          content:
            application/json:
              schema:
                type: string
  /spec.yaml:
    get:
      operationId: getSpecificationYaml
      description: Gets this specification in YAML format
      responses:
        '200':
          description: This specification
          content:
            application/x-yaml:
              schema:
                type: string
